// Function produces the n-th number in the look-and-say sequence.
// The look-and-say sequence is the sequence of numbers generated by describing each number to produce the next.

function lookAndSay (n) {
  let array = [1]

  function countNextArray () {
    const newArray = []
    let number = array[0]
    let count = 1
    for (let i = 1; i <= array.length; i++) {
      if (array[i] === number) {
        count = count + 1
      } else {
        newArray.push(count)
        newArray.push(number)
        number = array[i]
        count = 1
      }
    }
    array = newArray
  }

  for (let i = 0; i < n - 1; i++) {
    countNextArray([array])
  }

  const string = array.toString().replace(/,/g, '')
  return string
}
console.log(lookAndSay(7))
